info:
  app:
    name: ${name:hocs-topics-service}
    fullname: Hocs Topic Service
    version: ${version:0.0.1}

server:
  http2:
    enabled: true
  max-http-header-size: 1048576
  port: 8097
  shutdown: graceful

spring:
  main:
    banner-mode: off
  flyway:
    schemas: topics
    locations: classpath:/db/schema,classpath:/db/data
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:topics}&user=${db.username:root}&password=${db.password:dev}&stringtype=unspecified

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

hocs:
  case-service: http://localhost:8082

auditing:
  deployment:
    namespace: local
    name: ${info.app.name}

aws:
  sns:
    config:
      region: eu-west-2
    audit-search:
      account:
        access-key:
        secret-key:
        id:
        topic-name:
        arn: arn:aws:sns:${aws.sns.config.region}:${aws.sns.audit-search.account.id}:${aws.sns.audit-search.topic-name}
